site_name: 'Little-Yoda Decoer'
site_description: 'xx'
site_author: 'Sven Bursch-Osewold'

repo_url: https://github.com/littleyoda/littleyoda-DCC-Decoder


docs_dir: docs_source

site_dir: docs

theme: 
  name: 'windmill'
  custom_dir: 'theme'

plugins:
  - exclude:
      glob:
        - "*.md~"

markdown_extensions:
    - smarty
    - toc:
        permalink: True
    - sane_lists
    - nl2br
    - toc:
        baselevel: 3

nav:
- Home: index.md
- Präsentation: Praesentation/p.md
- Funktionsumfang: Entwicklung/Funktionsumfang.md
- Nutzung:
    - Erste Schritte: Nutzung/Erste-Schritte.md
    - Firmware Updates: Nutzung/Firmware-Updates.md
    - Konfiguration: Nutzung/Konfiguration.md
- Anwendungen:
    - DCC-Generator: 
        - Einführung: Anwendung/DCC-Generator/index.md
        - DRV8870: Anwendung/DCC-Generator/DCC_Generator_DRV8870.md
        - L298N: Anwendung/DCC-Generator/DCC_Generator_L298N.md
    - Weichendekoder: 
        - Einführung: Anwendung/Weichendekoder/USECASE_Weichendekoder.md
    - Lokdekoder:
        - BTS7960: Anwendung/Lokdekoder/Lokdekoder_BTS7960.md
        - DRV8870: Anwendung/Lokdekoder/Lokdekoder_DRV8870.md
        - D1 Motor Shield: Anwendung/Lokdekoder/Lokdekoder_D1Mini.md
    - Gleisstellwerk:
        - Einführung: Anwendung/Gleisstellwerk/Gleisstellwerk.md
    - Sound:
        - Einführung: Anwendung/Sound/Basic.md
- Basis Schaltungen:
    - DCC-Decoder: Hardware/DCC-Decoder.md
    - Susi: Hardware/Susi.md
- Entwicklung:
    - Übersicht: Anwendung/Übersicht.html
    - Framework: Entwicklung/Framework.md
    - Entwicklungsumgebung: 
      - Selber kompilieren: Entwicklung/Selber kompilieren.md
      - Nutzung PlatformIO: Entwicklung/Entwicklung PlatformIO.md
      - Nutzung PlatformIO (CLI): Entwicklung/Entwicklung PlatformIO CLI.md
    - Debuggen: Entwicklung/DebugSerial.md
- Erklärungen:
    - H-Bridge: Erklärungen/H-Bridge.md    
- FAQ: FAQ.md
- Forum: https://forum.open4me.de
